### ISSUE TITLE
请问ShortCutsUtils中addShortcut()的变量clasName是打漏了个s还是故意的

### ISSUE THREAD

**Issue by zhihaofans** [afkT/DevUtils#1]
你好，请问ShortCutsUtils中addShortcut()的变量clasName是不小心打漏了个s还是故意的 (className->clasName) ，在研究怎么用时发现少了个s

[ShortCutUtils.java#L65](https://github.com/afkT/DevUtils/blob/master/DevLibUtils/src/main/java/dev/utils/app/ShortCutUtils.java#L65)

**Comment by afkT** [comment]
习惯性打这个名字简写,  统一修改相关字符串的改为 className了

**Comment by zhihaofans** [comment]
@afkT 好的谢谢
