### ISSUE TITLE
能否出个android Q的文件存储操作等的适配

### ISSUE THREAD

**Issue by GXSZone** [afkT/DevUtils#14]
如题

**Comment by afkT** [comment]
Version 1.8.6 *(2019-12-25)*
----------------------------

* `[Feature]` 适配 Android Q 并重构 PathUtils 工具类, 提供适配思路以及增加 MediaStoreUtils 多媒体工具类用于外部存储适配操作

* `[Add]` MediaStoreUtils 多媒体工具类

* `[Change]` 更新 ContentResolverUtils 工具类代码, 拆分到 UriUtils、MediaStoreUtils

其实在 1.8.6 的版本已经进行适配了，只是每个工具类职能不同，进行细化拆分了 `PathUtils `、`UriUtils`、`ContentResolverUtils`、`MediaStoreUtils`

我可以按你的思路创建一个适配 Helper 类，用于以后 Android 适配相关快捷操作，不需要使用多个工具类搭配使用，每个功能直接一个方法解决
