### ISSUE TITLE
DateUtils.isInTimeHHmmss("7:00","7:00")

### ISSUE THREAD

**Issue by Jasperben** [afkT/DevUtils#22]
DateUtils.isInTimeHHmmss("7:00","7:00")返回false
如果startTime和endTime相同的话
startTime应该是为今天的时间  endTime应该为第二天的时间

**Comment by afkT** [comment]
调用方法错啦

`DateUtils.isInTimeHHmmss("07:00:01","07:00:01")` ：这个方法格式是 HH:mm:ss

`DateUtils.isInTimeHHmm("07:00","07:00")` ：这个方法格式是 HH:mm


应该调用 `DateUtils.isInTimeHHmm` 方法

可以修改当前时间为 `07:00` 并且调用 `DateUtils.isInTimeHHmm("07:00","07:00")` 就能看到返回 `true` 了

> 但是 startTime 和 endTime 相同的情况，目前是没有进行判断的，因为涉及到具体时间判断有 `DateUtils.isInDate()` 方法

我可以下个版本加下这个处理。（当前版本你可以先自行判断是否一样，一样则直接返回 true）

**Comment by Jasperben** [comment]
上面写错了  就是
DateUtils.isInTimeHHmmss("7:00:00","7:00:00")返回false

**Comment by afkT** [comment]
> 上面写错了 就是
> DateUtils.isInTimeHHmmss("07:00:00","07:00:00")返回false

目前是没有进行判断 startTime 和 endTime 相同的情况，得下个版本才能加上，可以在调用前自行判断 startTime 和 endTime 是否一样

**Comment by afkT** [comment]
好了，用这个（已同步至 Maven Central）

```java
// DevApp Android 工具类库
implementation 'io.github.afkt:DevAppX:2.2.4'
```
