### ISSUE TITLE
AlarmUtils.java

### ISSUE THREAD

**Issue by Jasperben** [afkT/DevUtils#26]
[AlarmUtils.java](https://github.com/afkT/DevUtils/blob/master/lib/DevApp/src/main/java/dev/utils/app/AlarmUtils.java)
建议增加requestCode 支持多个闹钟设置

**Comment by afkT** [comment]
好的，最近有点忙，等忙完我看下，顺便发版本。

**Comment by afkT** [comment]
这个已经加了，在新版本的时候会一起发，应该在这几天我发个新版本
