### ISSUE TITLE
DEV工具类，是否有清除缓存和计算缓存大小的方法？

### ISSUE THREAD

**Issue by sunjun2009311** [afkT/DevUtils#27]
我好像没发现有唉

**Comment by afkT** [comment]
有呢

* **本应用数据清除管理工具类 ->** [CleanUtils.java](https://github.com/afkT/DevUtils/blob/master/lib/DevApp/src/main/java/dev/utils/app/CleanUtils.java)

| 方法 | 注释 |
| :- | :- |
| cleanCache | 清除外部缓存 ( path /storage/emulated/0/android/data/package/cache ) |
| cleanAppCache | 清除内部缓存 ( path /data/data/package/cache ) |
| cleanAppFiles | 清除内部文件 ( path /data/data/package/files ) |
| cleanAppSp | 清除内部 SP ( path /data/data/package/shared_prefs ) |
| cleanAppDbs | 清除内部数据库 ( path /data/data/package/databases ) |
| cleanAppDbByName | 根据名称清除数据库 ( path /data/data/package/databases/dbName ) |
| cleanCustomDir | 清除自定义路径下的文件 |
| cleanApplicationData | 清除本应用所有的数据 |

* **SDCard 工具类 ->** [SDCardUtils.java](https://github.com/afkT/DevUtils/blob/master/lib/DevApp/src/main/java/dev/utils/app/SDCardUtils.java)

| 方法 | 注释 |
| :- | :- |
| isSDCardEnable | 判断 SDCard 是否正常挂载 |
| getSDCardFile | 获取 SDCard 外部存储路径 ( path /storage/emulated/0/ ) |
| getSDCardPath | 获取 SDCard 外部存储路径 ( path /storage/emulated/0/ ) |
| isSDCardEnablePath | 判断 SDCard 是否可用 |
| getSDCardPaths | 获取 SDCard 路径 |
| getAllBlockSize | 获取内置 SDCard 空间总大小 |
| getAllBlockSizeFormat | 获取内置 SDCard 空间总大小 |
| getAvailableBlocks | 获取内置 SDCard 空闲空间大小 |
| getAvailableBlocksFormat | 获取内置 SDCard 空闲空间大小 |
| getUsedBlocks | 获取内置 SDCard 已使用空间大小 |
| getUsedBlocksFormat | 获取内置 SDCard 已使用空间大小 |
| getBlockSizeInfos | 返回内置 SDCard 空间大小信息 |

**Comment by sunjun2009311** [comment]
en en 
通过路径去获取大小就可以啦
