### ISSUE TITLE
AppUtils

### ISSUE THREAD

**Issue by Jasperben** [afkT/DevUtils#28]
建议增加代码【获取所有已安装的应用】和【获取所有 能够显示在 桌面上的 应用】
获取所有已安装的应用
`private List<String> getInstalledPackages(Context context) {
        List<String> installedPackageList = new ArrayList<>();
        List<PackageInfo> installedPackageInfoList = context.getPackageManager().getInstalledPackages(PackageManager.MATCH_UNINSTALLED_PACKAGES);
        for (PackageInfo packageInfo: installedPackageInfoList) {
            installedPackageList.add(packageInfo.packageName);
        }
        return installedPackageList;
    }
`

获取所有 能够显示在 桌面上的 应用
`private List<String> getAllLauncherIconPackages(Context context) {
        List<String> launcherIconPackageList = new ArrayList<>();

        Intent intent = new Intent();
        intent.setAction(Intent.ACTION_MAIN);
        intent.addCategory(Intent.CATEGORY_LAUNCHER);

        //set MATCH_ALL to prevent any filtering of the results
        List<ResolveInfo> resolveInfos = context.getPackageManager().queryIntentActivities(intent, PackageManager.MATCH_ALL);
        for (ResolveInfo info: resolveInfos) {
            launcherIconPackageList.add(info.activityInfo.packageName);
        }

        return launcherIconPackageList;
    }
`

**Comment by afkT** [comment]
第二个方法添加了 [AppInfoUtils#getAllLauncherIconPackageNames](https://github.com/afkT/DevUtils/blob/master/lib/DevApp/src/main/java/dev/utils/app/info/AppInfoUtils.java#L389) 等我发个版本就可以用了
