### ISSUE TITLE
dev.utils.app.NetWorkUtils存在重复代码和被弃用代码

### ISSUE THREAD

**Issue by zhihaofans** [afkT/DevUtils#3]
1. [`NetworkInfo#isConnected()`](https://github.com/afkT/DevUtils/blob/1.5.9/DevLibUtils/src/main/java/dev/utils/app/NetWorkUtils.java#L112)在`Android API 28`中就是`nInfo.getState() == State.CONNECTED`

2. [`NetworkInfo#isAvailable()`](https://github.com/afkT/DevUtils/blob/1.5.9/DevLibUtils/src/main/java/dev/utils/app/NetWorkUtils.java#L202)在`Android API 28`被弃用了

3. `android.net.NetworkInfo`在`Android Q`会被弃用

官方文档: [android.net.NetworkInfo](https://developer.android.com/reference/android/net/NetworkInfo)

**Comment by afkT** [comment]
第一点修改啦，另外两点，看了下 API ，确实是会弃用，会在这两天内，处理一下 NetworkInfo 兼容问题，谢谢啦。

**Comment by afkT** [comment]
已经解决了，准备发个版本
