### ISSUE TITLE
电池电量信息

### ISSUE THREAD

**Issue by Jasperben** [afkT/DevUtils#30]
1.期待加入获取电量相关的封装
https://blog.csdn.net/qq_45146250/article/details/125314489
https://blog.51cto.com/u_14523369/6153404
https://www.orcode.com/question/784601_k5b833.html

2.LogPrintUtils感觉改为LogUtils更方便调用

**Comment by afkT** [comment]
1、新增 [BatteryUtils](https://github.com/afkT/DevUtils/blob/master/lib/DevApp/src/main/java/dev/utils/app/BatteryUtils.java) 电量管理工具类了，这几天发一个版本
2、那个 LogPrintUtils 是工具类内部打印 Android 模块日志的，你可以单独复制出来去使用

```java
// 整个工具类内部日志信息，都通过以下两个工具类输出打印，并且通过 DevUtils.openLog() 控制开关

// dev.utils.app - APP 日志打印工具类
LogPrintUtils

// dev.utils.common - Java Common 日志打印工具类
JCLogUtils
```
