### ISSUE TITLE
FileUtils

### ISSUE THREAD

**Issue by JiZhi-Error** [afkT/DevUtils#9]
如果可以的话，增加一个：是否拥有文件夹或文件读写的权限判断

**Comment by afkT** [comment]
> 如果可以的话，增加一个：是否拥有文件夹或文件读写的权限判断

ok，这个可以实现，我今晚加下。

**Comment by JiZhi-Error** [comment]
> > 如果可以的话，增加一个：是否拥有文件夹或文件读写的权限判断
> 
> ok，这个可以实现，我今晚加下。

我这刚好有用户卡出来神奇的bug

**Comment by afkT** [comment]
> > > 如果可以的话，增加一个：是否拥有文件夹或文件读写的权限判断
> > 
> > 
> > ok，这个可以实现，我今晚加下。
> 
> 我这刚好有用户卡出来神奇的bug

这个其实用 `File.canRead()`、`File.canWrite()` 可以实现，我今晚测试下 Android Q，以及 Q 以下版本有无读写权限返回结果区别

**Comment by JiZhi-Error** [comment]
> > > > 如果可以的话，增加一个：是否拥有文件夹或文件读写的权限判断
> > > 
> > > 
> > > ok，这个可以实现，我今晚加下。
> > 
> > 
> > 我这刚好有用户卡出来神奇的bug
> 
> 这个其实用 `File.canRead()`、`File.canWrite()` 可以实现，我今晚测试下 Android Q，以及 Q 以下版本有无读写权限返回结果区别

R那边我这目前写法还没测试，晚点我让我朋友试试看

**Comment by afkT** [comment]
已经添加了，`FileUtils#canRead、canWrite、canReadWrite`  如果急用你先 copy 代码，过几天我再发个版本，已经测试 Q、R 以及 Q 以下（是否允许读写权限）各种情况下，返回结果，都是正确的。
